export type ArchiveEntry={name:string;size:number;data:Uint8Array;date?:Date;source:string;hash?:string;duplicate?:boolean;planned?:string};
const u16=(v:DataView,o:number)=>v.getUint16(o,true),u32=(v:DataView,o:number)=>v.getUint32(o,true);
const safe=(n:string)=>n.replace(/\\/g,"/").replace(/^\/+/,"").split("/").filter(p=>p&&p!==".."&&p!==".").join("/");
const base=(n:string)=>n.split("/").pop()||n;
export const ext=(n:string)=>{const b=base(n),i=b.lastIndexOf(".");return i>0?b.slice(i+1).toLowerCase():""};
export function formatBytes(n:number){if(n<1024)return`${n} o`;if(n<1048576)return`${(n/1024).toFixed(1)} Ko`;if(n<1073741824)return`${(n/1048576).toFixed(1)} Mo`;return`${(n/1073741824).toFixed(1)} Go`}
export function detectFormat(f:File){const n=f.name.toLowerCase();if(n.endsWith(".tar.gz")||n.endsWith(".tgz"))return"TAR.GZ";if(n.endsWith(".zip"))return"ZIP";if(n.endsWith(".tar"))return"TAR";if(n.endsWith(".gz")||n.endsWith(".gzip"))return"GZIP";if(n.endsWith(".7z"))return"7Z";if(n.endsWith(".rar"))return"RAR";return"INCONNU"}
async function decompress(data:Uint8Array,format:"deflate-raw"|"gzip"){const stream=new Blob([data as BlobPart]).stream().pipeThrough(new DecompressionStream(format));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function compress(data:Uint8Array,format:"gzip"){const stream=new Blob([data as BlobPart]).stream().pipeThrough(new CompressionStream(format));return new Uint8Array(await new Response(stream).arrayBuffer())}
export async function readZip(file:File){const b=new Uint8Array(await file.arrayBuffer()),v=new DataView(b.buffer);let end=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(u32(v,i)===0x06054b50){end=i;break}if(end<0)throw Error("ZIP invalide ou incomplet.");let cur=u32(v,end+16);const out:ArchiveEntry[]=[],dec=new TextDecoder();for(let i=0;i<u16(v,end+10);i++){if(u32(v,cur)!==0x02014b50)throw Error("Structure ZIP non reconnue.");const method=u16(v,cur+10),cs=u32(v,cur+20),size=u32(v,cur+24),nl=u16(v,cur+28),el=u16(v,cur+30),cl=u16(v,cur+32),lo=u32(v,cur+42),name=safe(dec.decode(b.slice(cur+46,cur+46+nl))),start=lo+30+u16(v,lo+26)+u16(v,lo+28),packed=b.slice(start,start+cs);if(!name.endsWith("/")){if(method!==0&&method!==8)throw Error(`Compression ZIP non prise en charge : ${name}`);out.push({name,size,data:method===0?packed:await decompress(packed,"deflate-raw"),source:file.name})}cur+=46+nl+el+cl}return out}
function octal(bytes:Uint8Array){return parseInt(new TextDecoder().decode(bytes).replace(/\0.*$/,"").trim()||"0",8)||0}
export function readTarBytes(bytes:Uint8Array,source:string){const out:ArchiveEntry[]=[],dec=new TextDecoder();for(let o=0;o+512<=bytes.length;){if(bytes.slice(o,o+512).every(x=>x===0))break;const name=safe(dec.decode(bytes.slice(o,o+100)).replace(/\0.*$/,"")),size=octal(bytes.slice(o+124,o+136)),mtime=octal(bytes.slice(o+136,o+148)),type=bytes[o+156];o+=512;if(name&&type!==53)out.push({name,size,data:bytes.slice(o,o+size),date:mtime?new Date(mtime*1000):undefined,source});o+=Math.ceil(size/512)*512}return out}
export async function readArchive(file:File){const format=detectFormat(file),bytes=new Uint8Array(await file.arrayBuffer());if(format==="ZIP")return readZip(file);if(format==="TAR")return readTarBytes(bytes,file.name);if(format==="TAR.GZ")return readTarBytes(await decompress(bytes,"gzip"),file.name);if(format==="GZIP"){const name=file.name.replace(/\.(gz|gzip)$/i,"")||"fichier";const data=await decompress(bytes,"gzip");return[{name,size:data.length,data,source:file.name}]};if(format==="7Z"||format==="RAR")throw Error(`${format} détecté : analyse du format disponible, extraction non disponible dans ce navigateur.`);throw Error("Format non reconnu.")}
function p16(a:number[],v:number){a.push(v&255,v>>>8&255)}function p32(a:number[],v:number){a.push(v&255,v>>>8&255,v>>>16&255,v>>>24&255)}
function crc32(d:Uint8Array){let c=0xffffffff;for(const b of d){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^0xffffffff)>>>0}
export function makeZip(entries:ArchiveEntry[]){const enc=new TextEncoder(),local:number[]=[],central:number[]=[];let offset=0;for(const f of entries){const d=f.data,n=enc.encode(safe(f.planned||f.name)),crc=crc32(d);p32(local,0x04034b50);p16(local,20);p16(local,0x800);p16(local,0);p16(local,0);p16(local,0);p32(local,crc);p32(local,d.length);p32(local,d.length);p16(local,n.length);p16(local,0);local.push(...n,...d);p32(central,0x02014b50);p16(central,20);p16(central,20);p16(central,0x800);p16(central,0);p16(central,0);p16(central,0);p32(central,crc);p32(central,d.length);p32(central,d.length);p16(central,n.length);p16(central,0);p16(central,0);p16(central,0);p16(central,0);p32(central,0);p32(central,offset);central.push(...n);offset=local.length}const out=[...local,...central];p32(out,0x06054b50);p16(out,0);p16(out,0);p16(out,entries.length);p16(out,entries.length);p32(out,central.length);p32(out,local.length);p16(out,0);return new Uint8Array(out)}
function textField(text:string,length:number){const b=new TextEncoder().encode(text),out=new Uint8Array(length);out.set(b.slice(0,length));return out}
export function makeTar(entries:ArchiveEntry[]){const blocks:Uint8Array[]=[];for(const e of entries){const data=e.data,h=new Uint8Array(512),name=safe(e.planned||e.name);h.set(textField(name,100),0);h.set(textField("0000644\0",8),100);h.set(textField("0000000\0",8),108);h.set(textField("0000000\0",8),116);h.set(textField(data.length.toString(8).padStart(11,"0")+"\0",12),124);h.set(textField(Math.floor((e.date||new Date()).getTime()/1000).toString(8).padStart(11,"0")+"\0",12),136);h.fill(32,148,156);h[156]=48;h.set(textField("ustar\0",6),257);h.set(textField("00",2),263);const sum=h.reduce((a,b)=>a+b,0);h.set(textField(sum.toString(8).padStart(6,"0")+"\0 ",8),148);blocks.push(h,data,new Uint8Array((512-data.length%512)%512))}blocks.push(new Uint8Array(1024));const size=blocks.reduce((s,b)=>s+b.length,0),out=new Uint8Array(size);let o=0;for(const b of blocks){out.set(b,o);o+=b.length}return out}
export async function makeTarGz(entries:ArchiveEntry[]){return compress(makeTar(entries),"gzip")}
export async function hashEntries(entries:ArchiveEntry[]){const seen=new Map<string,number>();return Promise.all(entries.map(async(e)=>{const digest=await crypto.subtle.digest("SHA-256",e.data as BufferSource),hash=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");const count=seen.get(hash)||0;seen.set(hash,count+1);return{...e,hash,duplicate:count>0}}))}
export function planEntries(entries:ArchiveEntry[],pattern:string,organize:boolean){return entries.map((e,i)=>{const extension=ext(e.name),raw=base(e.name),stem=extension?raw.slice(0,-extension.length-1):raw,date=e.date||new Date(),renamed=(pattern||"{nom}.{extension}").replaceAll("{nom}",stem).replaceAll("{extension}",extension).replaceAll("{date}",date.toISOString().slice(0,10)).replaceAll("{numero}",String(i+1).padStart(3,"0")).replace(/\.$/,"");let folder="";if(organize){const types:{[k:string]:string}={jpg:"Images",jpeg:"Images",png:"Images",gif:"Images",pdf:"Documents",doc:"Documents",docx:"Documents",txt:"Documents",xls:"Tableurs",xlsx:"Tableurs",csv:"Tableurs",mp3:"Audio",wav:"Audio",mp4:"Vidéos",mov:"Vidéos",zip:"Archives",tar:"Archives",gz:"Archives"};folder=`${types[extension]||"Autres"}/${date.getFullYear()}`;}return{...e,planned:safe(folder?`${folder}/${renamed}`:renamed)}})}
export async function saveToFolder(entries:ArchiveEntry[]){const picker=(window as unknown as{showDirectoryPicker?:()=>Promise<FileSystemDirectoryHandle>}).showDirectoryPicker;if(!picker)throw Error("L’enregistrement direct n’est pas disponible dans ce navigateur.");const root=await picker();for(const e of entries){const parts=(e.planned||e.name).split("/"),file=parts.pop()!;let dir=root;for(const p of parts)dir=await dir.getDirectoryHandle(p,{create:true});const handle=await dir.getFileHandle(file,{create:true}),writer=await handle.createWritable();await writer.write(e.data as FileSystemWriteChunkType);await writer.close()}}
