"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import{Archive,CheckCircle2,ChevronRight,Clock3,Download,File,FileArchive,FolderOpen,FolderTree,HardDriveDownload,History,Info,Layers3,ListTree,RefreshCcw,Search,Settings2,ShieldCheck,Sparkles,Trash2,UploadCloud}from"lucide-react";
import{ArchiveEntry,detectFormat,ext,formatBytes,hashEntries,makeTar,makeTarGz,makeZip,planEntries,readArchive,saveToFolder}from"./archive-utils";
type Mode="extract"|"create";type HistoryItem={id:number,date:string,action:string,count:number,format:string};
const category=(n:string)=>{const x=ext(n);if(["jpg","jpeg","png","gif","svg"].includes(x))return"Image";if(["pdf","doc","docx","txt"].includes(x))return"Document";if(["xls","xlsx","csv"].includes(x))return"Tableur";if(["mp3","wav"].includes(x))return"Audio";if(["mp4","mov"].includes(x))return"Vidéo";return"Autre"};
function download(data:Uint8Array,name:string,type:string){const url=URL.createObjectURL(new Blob([data as BlobPart],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Home(){const[mode,setMode]=useState<Mode>("extract"),[sources,setSources]=useState<File[]>([]),[entries,setEntries]=useState<ArchiveEntry[]>([]),[pattern,setPattern]=useState("{nom}_{numero}.{extension}"),[organize,setOrganize]=useState(true),[output,setOutput]=useState("ZIP"),[name,setName]=useState("archive-organisee"),[view,setView]=useState<"tree"|"list">("tree"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[history,setHistory]=useState<HistoryItem[]>([]),[historyOpen,setHistoryOpen]=useState(false),[query,setQuery]=useState("");const input=useRef<HTMLInputElement>(null);
useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("archiveflow-history")||"[]"))}catch{}},[]);
const planned=useMemo(()=>planEntries(entries,pattern,organize),[entries,pattern,organize]),filtered=useMemo(()=>planned.filter(e=>(e.planned||e.name).toLowerCase().includes(query.toLowerCase())),[planned,query]),dupes=planned.filter(e=>e.duplicate).length,total=sources.reduce((s,f)=>s+f.size,0);
function addHistory(action:string,format:string){const item={id:Date.now(),date:new Date().toISOString(),action,count:planned.length,format},next=[item,...history].slice(0,25);setHistory(next);localStorage.setItem("archiveflow-history",JSON.stringify(next))}
async function addFiles(list:FileList|null){if(!list?.length)return;setBusy(true);setError("");try{const chosen=Array.from(list);setSources(p=>mode==="create"?[...p,...chosen]:chosen);let all:ArchiveEntry[]=[];if(mode==="extract"){for(const f of chosen){const format=detectFormat(f);if(format==="RAR"||format==="7Z"){all.push({name:`${f.name} — ${format} détecté (extraction indisponible)`,size:f.size,data:new Uint8Array(),source:f.name});continue}all.push(...await readArchive(f))}}else{all=[...entries,...await Promise.all(chosen.map(async f=>({name:f.name,size:f.size,data:new Uint8Array(await f.arrayBuffer()),date:new Date(f.lastModified),source:"Fichiers ajoutés"})))]}setEntries(await hashEntries(all))}catch(e){setError(e instanceof Error?e.message:"Impossible de traiter les fichiers.")}finally{setBusy(false)}}
function reset(next?:Mode){if(next)setMode(next);setSources([]);setEntries([]);setError("")}
async function produce(folder=false){if(!planned.length)return;setBusy(true);setError("");try{const usable=planned.filter(e=>e.data.length>0||e.size===0);if(folder){await saveToFolder(usable);addHistory(mode==="extract"?"Extraction":"Organisation","Dossier");return}if(mode==="extract"&&usable.length===1){download(usable[0].data,(usable[0].planned||usable[0].name).split("/").pop()!,"application/octet-stream");addHistory("Extraction","Fichier");return}let data:Uint8Array,filename:string,mime:string;if(output==="TAR"){data=makeTar(usable);filename=`${name}.tar`;mime="application/x-tar"}else if(output==="TAR.GZ"){data=await makeTarGz(usable);filename=`${name}.tar.gz`;mime="application/gzip"}else{data=makeZip(usable);filename=`${name}.zip`;mime="application/zip"}download(data,filename,mime);addHistory(mode==="extract"?"Extraction":"Création",output)}catch(e){setError(e instanceof Error?e.message:"Opération impossible.")}finally{setBusy(false)}}
const tree=useMemo(()=>{const groups=new Map<string,ArchiveEntry[]>();for(const e of filtered){const path=e.planned||e.name,folder=path.includes("/")?path.split("/").slice(0,-1).join(" / "):"Racine";groups.set(folder,[...(groups.get(folder)||[]),e])}return[...groups]},[filtered]);
return <main className="v2"><header className="v2bar"><a className="v2brand"><i><Archive/></i><span>Archive<b>Flow</b><small>MANAGER</small></span></a><nav><button className="on">Espace de travail</button><button onClick={()=>setHistoryOpen(true)}><History/>Historique</button><button onClick={()=>alert("Les profils de règles seront ajoutés dans une prochaine étape.")}><Settings2/>Paramètres</button></nav><strong><ShieldCheck/>Traitement local</strong></header>
<section className="v2wrap"><div className="v2title"><div><em>ESPACE DE TRAVAIL</em><h1>Organisez vos archives en toute confiance.</h1><p>Prévisualisez, renommez, classez et détectez les doublons avant de télécharger.</p></div><div className="formats"><span>ZIP <b>Complet</b></span><span>TAR/GZIP <b>Complet</b></span><span>7Z/RAR <b>Détection</b></span></div></div>
<div className="v2tabs"><button className={mode==="extract"?"on":""} onClick={()=>reset("extract")}><FolderOpen/>Extraire & organiser</button><button className={mode==="create"?"on":""} onClick={()=>reset("create")}><FileArchive/>Créer une archive</button></div>
<div className="dashboard"><aside className="controls"><section><h2><span>1</span>Fichiers sources</h2><input ref={input} hidden type="file" multiple accept={mode==="extract"?".zip,.tar,.gz,.tgz,.7z,.rar":undefined} onChange={e=>addFiles(e.target.files)}/><button className="dropmini" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><UploadCloud/><strong>{mode==="extract"?"Ajouter des archives":"Ajouter des fichiers"}</strong><small>Glissez-déposez ou parcourez</small></button>{sources.length>0&&<div className="source-summary"><b>{sources.length}</b><span>élément{sources.length>1?"s":""}<small>{formatBytes(total)}</small></span><button onClick={()=>reset()}><Trash2/></button></div>}</section>
<section><h2><span>2</span>Règles d’organisation</h2><label>Modèle de renommage<input value={pattern} onChange={e=>setPattern(e.target.value)}/><small>Variables : &#123;nom&#125; &#123;extension&#125; &#123;date&#125; &#123;numero&#125;</small></label><label className="check"><input type="checkbox" checked={organize} onChange={e=>setOrganize(e.target.checked)}/><i></i><span><b>Classer automatiquement</b><small>Type de fichier / année</small></span></label></section>
<section><h2><span>3</span>Destination</h2><label>Nom du résultat<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="formatselect">{["ZIP","TAR","TAR.GZ"].map(f=><button className={output===f?"on":""} key={f} onClick={()=>setOutput(f)}>{f}</button>)}</div></section></aside>
<section className="preview"><div className="previewhead"><div><h2>Simulation du résultat</h2><p>{planned.length} fichier{planned.length>1?"s":""} • {dupes} doublon{dupes>1?"s":""} détecté{dupes>1?"s":""}</p></div><div className="viewbuttons"><button className={view==="tree"?"on":""} onClick={()=>setView("tree")}><ListTree/></button><button className={view==="list"?"on":""} onClick={()=>setView("list")}><Layers3/></button></div></div><div className="search"><Search/><input placeholder="Rechercher dans le résultat…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<div className="v2error"><Info/>{error}</div>}{busy?<div className="v2empty"><RefreshCcw className="spin"/><b>Analyse en cours…</b></div>:!planned.length?<div className="v2empty"><FolderTree/><b>Aucun fichier à prévisualiser</b><p>Ajoutez des éléments pour générer le plan exact du résultat.</p></div>:view==="tree"?<div className="tree">{tree.map(([folder,items])=><div className="treegroup" key={folder}><h3><ChevronRight/><FolderOpen/>{folder}<span>{items.length}</span></h3>{items.map((e,i)=><FileRow e={e} key={(e.planned||e.name)+i}/>)}</div>)}</div>:<div className="tree listview">{filtered.map((e,i)=><FileRow e={e} key={(e.planned||e.name)+i}/>)}</div>}
<div className="resultbar"><div><span><CheckCircle2/>Simulation terminée</span><small>Aucun fichier original ne sera modifié.</small></div><button className="folderbtn" disabled={!planned.length||busy} onClick={()=>produce(true)}><HardDriveDownload/>Choisir un dossier</button><button className="downloadbtn" disabled={!planned.length||busy} onClick={()=>produce(false)}><Download/>Télécharger</button></div></section></div>
<div className="featurestrip"><span><Sparkles/><b>Renommage dynamique</b></span><span><FolderTree/><b>Classement type/date</b></span><span><ShieldCheck/><b>Doublons par SHA-256</b></span><span><Clock3/><b>Historique local</b></span></div></section>
{historyOpen&&<div className="modalback" onClick={()=>setHistoryOpen(false)}><div className="historypanel" onClick={e=>e.stopPropagation()}><div><h2>Historique local</h2><button onClick={()=>setHistoryOpen(false)}>×</button></div><p>Conservé uniquement dans ce navigateur.</p>{history.length?history.map(h=><article key={h.id}><i><History/></i><span><b>{h.action} — {h.format}</b><small>{h.count} fichiers • {new Date(h.date).toLocaleString("fr-FR")}</small></span></article>):<div className="nohistory">Aucune opération enregistrée.</div>}<button className="clearhistory" onClick={()=>{setHistory([]);localStorage.removeItem("archiveflow-history")}}>Effacer l’historique</button></div></div>}</main>}
function FileRow({e}:{e:ArchiveEntry}){return <div className={`v2row ${e.duplicate?"duplicate":""}`}><i><File/></i><div><b>{(e.planned||e.name).split("/").pop()}</b><small>{category(e.name)} • {formatBytes(e.size)} • {e.source}</small></div>{e.duplicate?<span className="dup">Doublon</span>:<CheckCircle2/>}</div>}
